export const BlockType = {
  Air: 0,
  Grass: 1,
  Dirt: 2,
  Stone: 3,
  RuneStone: 4,
  OakLog: 5,
  OakLeaves: 6,
  OakPlanks: 7,
  CraftingTable: 8,
  CoalOre: 9,
  IronOre: 10,
  Furnace: 11,
  Cobblestone: 12,
  Torch: 13,
  Sand: 14,
  Gravel: 15,
  Clay: 16,
  Snow: 17,
  Water: 18,
  Lava: 19,
  Ladder: 20,
  OakSapling: 21,
  TallGrass: 22,
  Dandelion: 23,
} as const;

export type BlockType = (typeof BlockType)[keyof typeof BlockType];
